version: '3.4'

services:
  payments-gateway:
    image: ${DOCKER_REGISTRY-}payments-gateway
    build:
      context: .
      dockerfile: src/PaymentsGateway/Dockerfile
    environment:
      - PAYMENTS_API_HOST=http://payments-api
    expose:
      - "8080"
    ports:
      - "5100:8080"
    depends_on:
     - payments-api

  payments-api:
    image: ${DOCKER_REGISTRY-}payments-api
    build:
      context: .
      dockerfile: src/PaymentsAPI/Dockerfile
    expose:
      - "8080"
    ports:
      - "5101:8080"